### ISSUE TITLE
Causes text to type backwards in some webforms

### ISSUE THREAD

**Issue by isaac-friedman** [pselle/millennials-to-snake-people#1]
When enabled in firefox 40.0, the cursor jumps to the beginning of the line after the first character typed, after every time backspace is pressed, and after the first keystroke replacing selected test. Observed in facebook comment fields and gmail quick replies. 
Observed not to occur in synchronous web forms.

It's a pity because, as a snake person, I liked having it enabled.

**Comment by mgwerner** [comment]
I can confirm this is happening to me as well.  Firefox 40.0.2.

When initially typing in a Gmail form, the first letter jumps before the cursor.  Does not happen in wrapped text, but continues after a hard return.  Makes the addon unusable, as typing emails is now tedious and frustrating.  Does not occur in Voat forum entry forms, only Gmail noted by this user.

**Comment by samuei** [comment]
Problem exists in Firefox 41.0.2, as well.

I tried typing (backwards, of course) milennials into a Facebook comment, and it was immediately updated in the box, live, to snake people. I suspect that either the add-on is constantly scanning for dynamic changes that warrant a replacement or that Facebook's comment fields are live-updating as they are typed, which is causing the behavior. 

A simple solution would be not to scan input fields in web pages at all, which seems like it would have minimal impact on users. A kludgier solution would be to automatically move the cursor in such fields to the end after each pass, but that might cause unexpected behavior (erasing default text, etc).

I really hope this is resolved soon, so I can go back to chuckling at news that comes across my Facebook feed.

**Comment by pselle** [comment]
Update on this – interestingly, Facebook and Gmail are _not_ input forms, which is why this is happening. Blame React? (and Google) In the meantime, I'm pondering how to check out the DOM to see if a user might be in one of these scenarios, and PRs are welcome

**Comment by pselle** [comment]
Pushed a fix for this, you can download the XPI from the repo here, the addon in the store is being reviewed. :)

**Comment by LindenWalsh** [comment]
Seeing this today in Gmail on Chrome 58.0.3029.81 on OSX 10.10.4
